apiVersion: v1
kind: Pod
metadata:
  name: app-with-secrets
  namespace: production
  labels:
    app: "test-app"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-credentials
          key: password
    - name: API_CONFIG
      valueFrom:
        configMapKeyRef:
          name: api-configuration
          key: config.json