apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    example.com/watch: "true"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: blocked-pod
  labels:
    example.com/watch: "true"
  annotations:
    example.com/block: "true"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80