apiVersion: v1
kind: Pod
metadata:
  name: allowed-pod
  labels:
    app: "test"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: blocked-pod
  labels:
    example.com/watch: "true"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80